### PR TITLE
elixir_client: Environment override

### PR DESCRIPTION
**Pull request by predrag-rakic**
Achieving behaviour similar to most unix tools: configuration can be set in config. file and can be overridden by environment variables.

Motivation: No need to put anything in config file, environment vars are automagically respected.

### CODE REVIEW

**Review by shiroyasha — CHANGES_REQUESTED** [review]
Looks awesome. But let me share a war story:

Rails automatically uses the `DATABASE_URL` environment variable if it is available. I have worked on one project, and I have set the `DATABASE_URL=<staging_environ_url>` and done some manual configuration, then, after lunch I have continued to work on a different project and the first thing I did was to pull the latest code and migrate my database.

This, to my horror executed the migration on the staging environment of the previous projects I was working on.

The seemingly magical behaviour would not happen if Rails didn't use environment variables.
Since then, I like to avoid needless magic.

Also, keep in mind that it could happen that we don't use the client directly, but wrap it in some other library that could potentially hide the need for environment variables.

**Comment by shiroyasha** [comment]
Maybe someone else has an opinion cc @nemanja-m @darkofabijan.

**Comment by shiroyasha** [comment]
To be clear. I am not totally agains this idea. I am just sharing some bad experiences with it.

Currently I am 50% - 50%.

**Comment by predrag-rakic** [comment]
What you described is potential problem that can happened any time anybody is working with env vars.
Solution to that situation is simple: lets not use environment.

If that solution is not acceptable (or more accurately not possible) than there is nothing new or more hazardous in this PR.

Examples are countless: `DISPLAY`, `EDITOR`, `AWS_ACCESS_KEY_ID`, `RELX_REPLACE_OS_VARS`, ...
Some more dangerous than others but that is how UNIX world works.

**Comment by predrag-rakic** [comment]
@shiroyasha 
What is the difference re war story between this PR and having:

```
config(:foo, host: {:system, "FOO_HOST"})
```

in config file?

**Comment by shiroyasha** [comment]
I would be able to setup my projects

``` elixir
# prod.config
config :foo, :bar, {:system, SOMETHING}

# dev.config
config :foo, :bar, "localhost"

# test.config
config :foo, :bar, "localhost"
```

and not worry about any side effects.

By doing this, it is also very straight forward to find what my application uses in production, precisely.

**Comment by shiroyasha** [comment]
I propose the following:

This change seems to be the least of the priorities in this project. Testing, generating clients, running them in rails projects, publishing, etc... are far more important.

Let's leave this PR open, and we can come back to this question when the rest of the issues are solved.

**Comment by predrag-rakic** [comment]
> By doing this, it is also very straight forward to find what my application uses in production, precisely.

Any code that can be auto-generated is just boilerplate code and should be auto-generated and documented. 

> Let's leave this PR open, and we can come back to this question when the rest of the issues are solved.

No. That means never.
Lets merge it and make Trelo note to revisit it when the rest of the issues are solved.

Now seriously, we can reverse priorities so that env var is automatically imported only if there is no record in config file?

**Comment by shiroyasha** [comment]
@predrag-rakic you are right, this PR is time consuming.

My only objection is that I can only find examples of CLI tools that read configuration from the environment, client libraries almost always rely on the application to pass the configuration.

Feel free to merge the PR 👍  But if possible, don't rely on this behaviour while writing tests for clients.

**Pull request closed without merging**
